apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu-sleeper
  name: ubuntu-sleeper
  namespace: capabilities
spec:
  securityContext:
    runAsUser: 0
  containers:
  - command:
    - sleep
    - "4800"
    image: ubuntu
    name: ubuntu-sleeper
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
