apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-falco
  name: nginx-falco
spec:
  nodeName: kubeworker01
  containers:
    - image: nginx
      name: nginx-falco
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}