apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd-deploy
  name: httpd-service
  namespace: httpd
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30001
  selector:
    app: httpd-deploy
  type: NodePort